### PR TITLE
Use `prop-types` instead of `React.PropTypes`

### PR DESCRIPTION
**Pull request by fabiancook**

### CODE REVIEW

**Comment by fabiancook** [comment]
I can confirm with these changes that this module works with React 16

**Comment by dragfire** [comment]
@fabiancook Thanks for the PR. Cheers!

**Comment by fabiancook** [comment]
Following up on this, will there be a push to npm with a new version?

**Comment by dragfire** [comment]
Sorry, forgot to do that. I will update you on that as soon as it is published.

**Comment by fabiancook** [comment]
Hi, is there any update here? Thanks

**Comment by dragfire** [comment]
@fabiancook just published with the latest changes on npm. Sorry for the delay.

**Comment by fabiancook** [comment]
Thanks, would be good to see the distributed version up on GitHub as well for consistency :).

**Pull request merged**
